[package]
name = "cofd-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_with = "3.3"

strum = { version = "0.25", features = ["derive"] }
