[package]
name = "cofd-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true

chrono = { version = "0.4", features = ["serde"] }
strum = { version = "0.25", features = ["derive"] }

thiserror = "1"
