[package]
name = "cofd-meta"
version = "0.1.0"
edition.workspace = true

[dependencies]
cofd-schema.workspace = true
regex.workspace = true

serde = { workspace = true, features = ["derive"] }
serde_regex = "1"